# Fixme2_py

On line 22, the attempted comparison only has 1 equal sign, this should obviously be two. Fix this and run the file.

```shell
$ python3 fixme2.py 
That is correct! Here's your flag: picoCTF{3qu4l1ty_n0t_4551gnm3nt_f6a5aefc}
```